# Generated by Django 5.1.2 on 2024-10-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('genuine', 'Genuine'), ('fake', 'Fake'), ('used', 'Used')], default='genuine', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('genuine', 'Genuine'), ('fake', 'Fake'), ('used', 'Used')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('queried_by', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtech.product')),
            ],
        ),
    ]
